extends SceneTree

const EmberHero := preload("res://scripts/hero.gd")
const HeroPackSpec := preload("res://scripts/hero_pack_spec.gd")
const HeroPackCatalog := preload("res://scripts/hero_pack_catalog.gd")


func _init() -> void:
	create_timer(90.0).timeout.connect(func() -> void: quit(1))
	call_deferred("_run")


func _run() -> void:
	var hero := EmberHero.new()
	hero.name = "PackHero"
	root.add_child(hero)
	await process_frame
	hero.apply_hero_kind(&"ember_hero")
	assert(hero.hero_kind == &"ember_hero")
	assert(hero.hero_id == &"ember_hero")
	assert(hero.visual_pack_id == &"ember_hero")
	var actor := hero.get_node_or_null("XSXBHeroActor")
	assert(actor != null, "knight actor exists")
	assert(str(actor.get("frame_profile_id")) == "ember_hero")
	assert(hero._clip_name(&"idle") == "idle")
	assert(hero._clip_name(&"run") == "run")
	hero.apply_hero_kind(&"assassin")
	await process_frame
	assert(hero.hero_kind == &"assassin")
	assert(hero.visual_pack_id == &"assassin")
	actor = hero.get_node_or_null("XSXBHeroActor")
	assert(str(actor.get("frame_profile_id")) == "ember_assassin")
	assert(hero._clip_name(&"run") == "run")
	assert(hero._clip_name(&"dash") == "skill_cast")
	assert(hero.call("_hides_held_overlay") == true, "assassin hides the hold-sword overlay")
	hero.weapon_slots = [&"sword", &"pistol"] as Array[StringName]
	assert(hero.select_weapon_slot(1))
	await process_frame
	assert(hero.call("_hides_held_overlay") == false, "assassin still floats guns")
	var held := hero.find_child("HeldWeapon", true, false) as Sprite2D
	assert(held != null and held.visible and held.texture != null, "assassin gun overlay exists")
	assert(hero.select_weapon_slot(0))
	assert(hero.call("_hides_held_overlay") == true, "assassin melee hides overlay again")
	assert(HeroPackSpec.clip_name("idle", "assassin", "three", "front") == "idle_front")
	hero.apply_hero_kind(&"ember_hero", &"frost_warrior")
	await process_frame
	assert(hero.visual_pack_id == &"frost_warrior")
	assert(hero.get("_view_mode") == "three")
	assert(hero.get("_view") == &"side")
	assert(hero._clip_name(&"idle") == "idle_side", "combat frost stays on side")
	assert(hero._clip_name(&"dash") == "skill_cast_side", "frost skill uses skill_cast")
	assert(hero.call("_hides_held_overlay") == true, "unarmed frost hides the hold-sword overlay")
	var frost_actor := hero.get_node_or_null("XSXBHeroActor")
	assert(frost_actor != null)
	var cast_clip := float(frost_actor.call("animation_duration", "skill_cast_side"))
	assert(cast_clip > 0.0, "frost transform clip exists")
	var cast_hold := float(hero.call("_skill_input_hold", &"skill_cast_side", 0.80))
	assert(cast_hold <= EmberHero.SKILL_INPUT_LOCK_CAP + 0.001, "transform input lock must be capped at 1.2s")
	assert(is_equal_approx(cast_hold, minf(cast_clip, EmberHero.SKILL_INPUT_LOCK_CAP)), "hold uses min(clip, cap)")
	assert(HeroPackCatalog.transform_into(&"frost_warrior") == &"frost_armed")
	assert(not HeroPackCatalog.selectable_skin_ids(&"ember_hero").has(&"frost_armed"), "armed form is hidden from picker")
	assert(HeroPackCatalog.can_apply_pack(&"ember_hero", &"frost_armed"), "combat can still apply the armed form")
	hero.has_dash = true
	hero.dash_cooldown_left = 0.0
	hero.skill_levels[&"ember_hero"] = 2
	assert(is_equal_approx(float(hero.call("skill_size_mult")), 1.0), "unarmed frost does not grow")
	hero.skill_levels[&"ember_hero"] = 0
	hero.call("request_dash")
	assert(bool(hero.get("_transforming")), "frost skill starts a transform")
	hero.call("_update_dash", EmberHero.SKILL_INPUT_LOCK_CAP - 0.05)
	assert(bool(hero.get("_transforming")), "cast still holds before the 1.2s unlock")
	assert(hero.visual_pack_id == &"frost_warrior", "pack stays unarmed during the locked cast")
	assert(bool(hero.call("_skill_controls_locked")), "controls stay locked until the 1.2s cap")
	hero.call("_update_dash", 0.10)
	assert(hero.visual_pack_id == &"frost_armed", "long skill_cast commits the armed pack at the 1.2s unlock")
	assert(float(hero.get("_dash_elapsed")) < 0.0, "dash clears when the armed pack commits")
	assert(not bool(hero.get("_transforming")))
	assert(not bool(hero.call("_skill_controls_locked")), "controls unlock with the armed pack")
	assert(bool(hero.call("is_frost_accept_guarded")), "T1.2 starts the 3s accept guard")
	var hp_guard := hero.health
	hero.set("_hit_invuln", 0.0)
	hero.set("_dash_invuln", 0.0)
	hero.take_damage(999)
	assert(hero.health == hp_guard, "frost accept guard blocks damage for the capture window")
	assert(not hero.is_down, "downed frame during the 3s window is accept FAIL evidence")
	hero.call("_tick_frost_accept_guard", EmberHero.FROST_ACCEPT_GUARD + 0.05)
	assert(not bool(hero.call("is_frost_accept_guarded")), "accept guard is 3s, not the whole 8s form")
	assert(hero.form_left > EmberHero.FROST_ACCEPT_GUARD, "armed form continues after the 3s shield")
	hero.take_damage(10)
	assert(hero.health < hp_guard, "hero can die after the 3s accept guard")
	hero.health = hp_guard
	hero.set("_hit_invuln", 0.0)
	var armed_origin := hero.position
	hero.move_in_direction(Vector2.RIGHT, 0.30)
	hero.call("_update_animation_state")
	assert(hero.position.x >= armed_origin.x + 24.0, "armed walk displaces far enough for a MOVE frame")
	assert(hero.current_state == &"run", "armed walk plays the run clip")
	assert(str(hero.get_node("XSXBHeroActor").get("_current_animation")).begins_with("run"), "armed MOVE frame is run_side")
	hero.position = armed_origin
	hero.set("_move_input", Vector2.ZERO)
	hero.call("_set_state", &"idle")
	hero.skill_levels[&"ember_hero"] = 2
	hero.call("_refresh_combat_visual_scale")
	assert(is_equal_approx(float(hero.call("form_damage_mult")), 1.40), "armed form damage scales with skill")
	assert(is_equal_approx(float(hero.call("skill_size_mult")), EmberHero.FROST_SKILL_SIZE * EmberHero.FROST_SKILL_SIZE), "armed form skill_size_mult grows per skill")
	assert(is_equal_approx(float(hero.call("combat_visual_scale")), EmberHero.COMBAT_VISUAL_SCALE), "frost skill_size_mult does not scale the sprite")
	assert(int(hero.call("dash_strike_damage")) == EmberHero.scale_damage(EmberHero.DASH_DAMAGE, 100, 1.0, 1.0, 1.40, 1.0), "frost dash does not also take knight +12")
	hero.skill_levels[&"ember_hero"] = 0
	hero.call("_refresh_combat_visual_scale")
	hero.call("_apply_view_from_move", Vector2(0.0, 1.0))
	assert(hero.get("_view") == &"side", "combat ignores south view")
	assert(hero._clip_name(&"run") == "run_side")
	hero.call("_apply_view_from_move", Vector2(0.0, -1.0))
	assert(hero._clip_name(&"jump") == "jump_side", "combat jump stays side")
	assert(is_equal_approx(hero.form_left, EmberHero.FROST_FORM_DURATION), "armed form starts an 8s timer")
	var armed_now := hero.get_node_or_null("XSXBHeroActor")
	assert(armed_now != null)
	var bubble_clip := float(armed_now.call("animation_duration", "skill_bubble_side"))
	assert(bubble_clip > 0.0, "untransform clip exists")
	var bubble_hold := float(hero.call("_skill_input_hold", &"skill_bubble_side", 0.80))
	assert(bubble_hold <= EmberHero.SKILL_INPUT_LOCK_CAP + 0.001, "revert input lock must be capped at 1.2s")
	hero.form_left = 0.0
	hero.call("_tick_frost_form", 0.05)
	assert(bool(hero.get("_reverting")), "timer expiry starts untransform")
	assert(hero._clip_name(&"dash") == "skill_bubble_side")
	hero.call("_update_dash", EmberHero.SKILL_INPUT_LOCK_CAP + 0.05)
	assert(bool(hero.get("_reverting")), "bubble clip may continue after input unlock")
	assert(not bool(hero.call("_skill_controls_locked")), "controls unlock during bubble at 1.2s")
	hero.call("_update_dash", maxf(bubble_clip - EmberHero.SKILL_INPUT_LOCK_CAP, 0.0) + 0.05)
	assert(hero.visual_pack_id == &"frost_warrior", "untransform returns when bubble ends")
	assert(not bool(hero.get("_reverting")))
	hero.apply_hero_kind(&"ember_hero", &"frost_armed")
	await process_frame
	assert(not bool(hero.call("is_frost_accept_guarded")), "applying the armed pack is not an accept i-frame")
	hero.form_left = 0.0
	hero.call("_tick_frost_form", 0.05)
	assert(bool(hero.get("_reverting")), "expiry starts untransform before down")
	hero.call("_start_down")
	assert(hero.visual_pack_id == &"frost_warrior", "down during untransform snaps to unarmed")
	assert(not bool(hero.get("_reverting")))
	hero.is_down = false
	hero.apply_hero_kind(&"ember_hero", &"frost_armed")
	await process_frame
	hero.form_left = 0.0
	hero.set("_queued_dash", true)
	hero.set("_jump_elapsed", -1.0)
	hero.call("_flush_action_queue")
	assert(bool(hero.get("_reverting")), "queued skill after expiry untransforms")
	assert(hero._clip_name(&"dash") == "skill_bubble_side")
	hero.call("_update_dash", float(hero.get_node("XSXBHeroActor").call("animation_duration", "skill_bubble_side")) + 0.05)
	assert(hero.visual_pack_id == &"frost_warrior", "queued expiry does not keep the armed pack")
	hero.apply_hero_kind(&"ember_hero", &"frost_armed")
	await process_frame
	hero.form_left = 0.0
	hero.set("_jump_elapsed", 0.10)
	hero.set("_jump_offset", -16.0)
	hero.call("_tick_frost_form", 0.05)
	assert(bool(hero.get("_reverting")), "expiry cancels jump into untransform")
	assert(float(hero.get("_jump_elapsed")) < 0.0)
	hero.call("_update_dash", 3.0)
	assert(hero.visual_pack_id == &"frost_warrior")
	hero.apply_hero_kind(&"ember_hero", &"frost_warrior")
	await process_frame
	hero.has_dash = true
	hero.dash_cooldown_left = 0.0
	hero.call("request_dash")
	assert(bool(hero.get("_transforming")), "unarmed frost skill starts transform")
	hero.call("_start_down")
	assert(hero.visual_pack_id == &"frost_warrior", "down during transform-in stays unarmed")
	assert(not bool(hero.get("_transforming")))
	hero.is_down = false
	hero.apply_hero_kind(&"ember_hero", &"frost_armed")
	await process_frame
	hero.form_left = 4.0
	hero.call("_start_down")
	assert(hero.visual_pack_id == &"frost_armed", "down with form time left stays armed")
	hero.is_down = false
	hero.apply_hero_kind(&"ember_hero", &"frost_armed")
	await process_frame
	assert(hero.visual_pack_id == &"frost_armed")
	assert(hero.get("_view_mode") == "three")
	assert(hero._clip_name(&"idle") == "idle_side")
	assert(hero._clip_name(&"dash") == "dash_side", "armed frost skill uses the dash clip")
	assert(hero.call("_hides_held_overlay") == true, "baked greatsword hides hold overlay")
	var armed_actor := hero.get_node_or_null("XSXBHeroActor")
	assert(armed_actor != null)
	assert(str(armed_actor.get("frame_profile_id")) == "frost_armed")
	assert(float(armed_actor.call("animation_duration", "dash_side")) > 0.0, "armed dash clip exists")
	var armed_anims: Dictionary = armed_actor.get("_animations")
	assert(int((armed_anims.get("run_side", {}) as Dictionary).get("fps", 0)) == 16, "armed run uses pack slot_fps 16")
	assert(int((armed_anims.get("attack_side", {}) as Dictionary).get("fps", 0)) == 24, "armed attack uses native 24fps video frames")
	assert(((armed_anims.get("attack_side", {}) as Dictionary).get("frames", []) as Array).size() >= 8, "armed attack has a multi-frame slash")
	var armed_attack_n: int = ((armed_anims.get("attack_side", {}) as Dictionary).get("frames", []) as Array).size()
	var armed_combo: Array = hero.get("_combo_end")
	var slash_window: Vector2i = hero.call("_slash_read_window", armed_attack_n)
	assert(int(armed_combo[0]) == slash_window.y, "armed slash uses the readable sword window")
	assert(int(hero.get("_followup_start")) == slash_window.x, "armed follow-up replays from the slash window")
	assert(slash_window.x >= 8, "armed slash skips the idle-like windup")
	hero.call("request_jump")
	assert(hero.current_state == &"jump", "armed jump switches off idle")
	var jump_actor := hero.get_node("XSXBHeroActor")
	assert(str(jump_actor.get("_current_animation")).begins_with("jump"), "armed jump plays the jump clip")
	hero.call("_update_jump", 0.22)
	assert(float(hero.get("_jump_offset")) < -16.0, "armed jump air wall stays on JUMP_HEIGHT")
	assert(float(hero.get("_jump_visual_offset")) < -28.0, "armed jump sprite lift is screenshot-visible")
	assert(int(jump_actor.get("_current_frame")) >= 2, "armed jump holds a tucked-leg frame")
	hero.call("_cancel_jump")
	hero.call("request_attack")
	assert(hero.current_state == &"attack", "armed attack switches off idle")
	var atk_actor := hero.get_node("XSXBHeroActor")
	assert(str(atk_actor.get("_current_animation")).begins_with("attack"), "armed attack plays the slash clip")
	assert(int(atk_actor.get("_current_frame")) >= slash_window.x, "armed attack starts on the extended-sword window")
	assert(((armed_anims.get("run_front", {}) as Dictionary).get("frames", []) as Array).size() >= 4, "armed run front is a walk cycle")
	hero.call("_finish_combo")
	hero.apply_hero_kind(&"ember_hero")
	await process_frame
	var default_combo: Array = hero.get("_combo_end")
	assert(int(default_combo[0]) == 6 and int(default_combo[1]) == 19, "default knight keeps the two-hit strip windows")
	hero.apply_hero_kind(&"ember_hero", &"frost_armed")
	await process_frame
	hero.hub_hide_weapon = true
	hero.call("_apply_view_from_move", Vector2(0.0, 1.0))
	assert(hero.get("_view") == &"front", "home walker can face south")
	assert(hero._clip_name(&"idle") == "idle_front")
	hero.call("_apply_view_from_move", Vector2(0.0, -1.0))
	assert(hero._clip_name(&"idle") == "idle_back")
	hero.apply_hero_kind(&"ember_hero", &"frost_armed")
	assert(hero.visual_pack_id == &"frost_warrior", "home walker never keeps the armed form")
	hero.queue_free()
	print("HERO PACK RUNTIME PASS")
	quit()
